import * as fs from "fs";
import * as path from "path";
import { OpenAPISpec, ParsedEndpoint } from "../types";
import { toCamelCase, toPascalCase } from "../utils/schema";

function buildFetchFunction(ep: ParsedEndpoint): string {
  const lines: string[] = [];

  const args: string[] = ["config"];
  const pathParamArgs = ep.pathParams.map((p) => toCamelCase(p.name));
  const hasBody = !!ep.requestBodySchema;
  const hasQuery = ep.queryParams.length > 0;

  // JSDoc
  if (ep.summary || ep.description) {
    lines.push(`/**`);
    if (ep.summary) lines.push(` * ${ep.summary}`);
    if (ep.description) lines.push(` * ${ep.description}`);
    if (ep.deprecated) lines.push(` * @deprecated`);
    lines.push(` */`);
  }

  // Destructure params
  const destructured = [
    ...pathParamArgs,
    hasBody ? "body" : null,
    hasQuery ? "params" : null,
  ].filter(Boolean);

  const fnArgs = destructured.length > 0
    ? `{ ${destructured.join(", ")} } = {}`
    : "";

  const allArgs = fnArgs ? `config, ${fnArgs}` : "config";
  lines.push(`export async function ${toCamelCase(ep.operationId)}(${allArgs}) {`);

  // URL construction
  const pyPath = ep.path.replace(/{(\w+)}/g, (_, n) => `\${${toCamelCase(n)}}`);
  lines.push(`  const url = new URL(\`\${config.baseUrl}${pyPath}\`);`);

  if (hasQuery) {
    lines.push(`  if (params) {`);
    for (const p of ep.queryParams) {
      const camel = toCamelCase(p.name);
      lines.push(`    if (params.${camel} !== undefined) url.searchParams.set('${p.name}', String(params.${camel}));`);
    }
    lines.push(`  }`);
  }

  lines.push(`  const res = await fetch(url.toString(), {`);
  lines.push(`    method: '${ep.method}',`);
  lines.push(`    headers: { 'Content-Type': 'application/json', ...config.headers },`);
  if (hasBody) {
    lines.push(`    ...(body !== undefined && { body: JSON.stringify(body) }),`);
  }
  lines.push(`  });`);
  lines.push(`  if (!res.ok) {`);
  lines.push(`    const message = await res.text().catch(() => res.statusText);`);
  lines.push(`    throw new Error(\`\${res.status} \${message}\`);`);
  lines.push(`  }`);
  lines.push(`  if (res.status === 204) return undefined;`);
  lines.push(`  return res.json();`);
  lines.push(`}`);

  return lines.join("\n");
}

function groupByTag(endpoints: ParsedEndpoint[]): Map<string, ParsedEndpoint[]> {
  const map = new Map<string, ParsedEndpoint[]>();
  for (const ep of endpoints) {
    const tag = ep.tags[0] ?? "default";
    if (!map.has(tag)) map.set(tag, []);
    map.get(tag)!.push(ep);
  }
  return map;
}

export function generateFetchClient(
  spec: OpenAPISpec,
  endpoints: ParsedEndpoint[],
  outputDir: string,
  packageName: string
): void {
  fs.mkdirSync(outputDir, { recursive: true });

  const baseUrl = spec.servers?.[0]?.url ?? "https://api.example.com";
  const tagGroups = groupByTag(endpoints);

  // ── config.js ─────────────────────────────────────────────────────────────
  const configContent = `// Auto-generated by sdkgen. Do not edit.

/**
 * Create a client config object.
 * @param {string} baseUrl
 * @param {Record<string,string>} [headers]
 */
export function createConfig(baseUrl = '${baseUrl}', headers = {}) {
  return { baseUrl: baseUrl.replace(/\\/$/, ''), headers };
}
`;
  fs.writeFileSync(path.join(outputDir, "config.js"), configContent);

  // ── one file per tag ──────────────────────────────────────────────────────
  const moduleFiles: string[] = ["config"];

  for (const [tag, eps] of tagGroups) {
    const fileName = toCamelCase(tag);
    moduleFiles.push(fileName);

    let content = `// Auto-generated by sdkgen. Do not edit.\n\n`;
    content += eps.map(buildFetchFunction).join("\n\n") + "\n";

    fs.writeFileSync(path.join(outputDir, `${fileName}.js`), content);
  }

  // ── index.js ──────────────────────────────────────────────────────────────
  let indexContent = `// Auto-generated by sdkgen. Do not edit.\n\n`;
  for (const file of moduleFiles) {
    indexContent += `export * from './${file}.js';\n`;
  }

  // Also export a factory that groups everything nicely
  const sdkName = toPascalCase(packageName);
  indexContent += `\n/**\n * Factory: create a grouped API client.\n * @param {string} baseUrl\n * @param {Record<string,string>} headers\n */\nexport function create${sdkName}(baseUrl, headers = {}) {\n`;
  indexContent += `  const config = { baseUrl: (baseUrl || '${baseUrl}').replace(/\\/$/, ''), headers };\n`;
  indexContent += `  return {\n`;

  for (const [tag, eps] of tagGroups) {
    const fileName = toCamelCase(tag);
    indexContent += `    ${toCamelCase(tag)}: {\n`;
    for (const ep of eps) {
      indexContent += `      ${toCamelCase(ep.operationId)}: (...args) => { const [opts, ...rest] = args; return ${toCamelCase(ep.operationId)}(config, opts, ...rest); },\n`;
    }
    indexContent += `    },\n`;
    // We need the named imports; handled by the wildcard export above.
    void fileName;
  }

  indexContent += `  };\n}\n`;
  fs.writeFileSync(path.join(outputDir, "index.js"), indexContent);

  // ── package.json ──────────────────────────────────────────────────────────
  const pkg = {
    name: `${packageName}-fetch`,
    version: "0.1.0",
    description: `Fetch client for ${spec.info.title}`,
    type: "module",
    main: "index.js",
    exports: { ".": "./index.js" },
  };
  fs.writeFileSync(path.join(outputDir, "package.json"), JSON.stringify(pkg, null, 2));

  // ── README.md ─────────────────────────────────────────────────────────────
  const firstTag = [...tagGroups.keys()][0];
  const firstEp = endpoints[0];

  const readme = `# ${spec.info.title} — Fetch Client

> Auto-generated by **sdkgen** v0.1.0. No dependencies, works in browsers and Node.js ≥ 18.

## Install

\`\`\`bash
npm install .
\`\`\`

## Usage

\`\`\`js
import { create${sdkName} } from '${packageName}-fetch';

const api = create${sdkName}('${baseUrl}', {
  Authorization: 'Bearer YOUR_TOKEN',
});

${firstEp && firstTag ? `const result = await api.${toCamelCase(firstTag)}.${toCamelCase(firstEp.operationId)}();` : ""}
\`\`\`

## Modules

${[...tagGroups.keys()].map((t) => `- \`${toCamelCase(t)}\``).join("\n")}
`;
  fs.writeFileSync(path.join(outputDir, "README.md"), readme);
}
