import * as fs from "fs";
import * as path from "path";
import { OpenAPISpec, ParsedEndpoint, SchemaObject } from "../types";
import { toSnakeCase, toPascalCase } from "../utils/schema";
import { resolveSchema } from "../parsers/parser";

function schemaToPyType(schema: SchemaObject | undefined, spec: OpenAPISpec, depth = 0): string {
  if (!schema) return "Any";
  const resolved = resolveSchema(schema, spec);
  if (!resolved) return "Any";

  if (resolved.enum) {
    return resolved.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  switch (resolved.type) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "number":
      return "float";
    case "boolean":
      return "bool";
    case "array":
      return `List[${schemaToPyType(resolved.items, spec, depth + 1)}]`;
    case "object":
      return "Dict[str, Any]";
    default:
      return "Any";
  }
}

function schemaToDataclass(name: string, schema: SchemaObject, spec: OpenAPISpec): string {
  const resolved = resolveSchema(schema, spec);
  if (!resolved || resolved.type !== "object" || !resolved.properties) {
    return `${name} = Any\n`;
  }

  const required = resolved.required ?? [];
  const lines: string[] = [`@dataclass`, `class ${name}:`];

  // Required fields first, then optional
  const entries = Object.entries(resolved.properties);
  const reqEntries = entries.filter(([k]) => required.includes(k));
  const optEntries = entries.filter(([k]) => !required.includes(k));

  for (const [key, val] of [...reqEntries, ...optEntries]) {
    const pyType = schemaToPyType(val, spec);
    const isOpt = !required.includes(key);
    const fieldType = isOpt ? `Optional[${pyType}]` : pyType;
    const default_ = isOpt ? " = None" : "";
    const docStr = val.description ? `  # ${val.description}` : "";
    lines.push(`    ${toSnakeCase(key)}: ${fieldType}${default_}${docStr}`);
  }

  if (lines.length === 2) lines.push("    pass");
  return lines.join("\n") + "\n";
}

function buildPyMethod(ep: ParsedEndpoint, spec: OpenAPISpec): string {
  const lines: string[] = [];

  const args: string[] = ["self"];
  for (const p of ep.pathParams) {
    const pyType = p.schema ? schemaToPyType(p.schema, spec) : "str";
    args.push(`${toSnakeCase(p.name)}: ${pyType}`);
  }
  if (ep.requestBodySchema) {
    const t = schemaToPyType(ep.requestBodySchema, spec);
    const opt = ep.requestBodyRequired ? "" : " = None";
    args.push(`body: ${t}${opt}`);
  }
  if (ep.queryParams.length > 0) {
    args.push(`params: Optional[Dict[str, Any]] = None`);
  }

  const returnType = "Any";
  const methodName = toSnakeCase(ep.operationId);

  if (ep.summary) {
    lines.push(`    def ${methodName}(${args.join(", ")}) -> ${returnType}:`);
    lines.push(`        """${ep.summary}${ep.description ? `\n\n        ${ep.description}` : ""}"""`);
  } else {
    lines.push(`    def ${methodName}(${args.join(", ")}) -> ${returnType}:`);
  }

  // Build URL
  const pyPath = ep.path.replace(/{(\w+)}/g, (_, n) => `{${toSnakeCase(n)}}`);
  lines.push(`        url = f"{self.base_url}${pyPath}"`);

  // Kwargs
  lines.push(`        kwargs: Dict[str, Any] = {}`);
  if (ep.queryParams.length > 0) {
    lines.push(`        if params:`);
    lines.push(`            kwargs["params"] = params`);
  }
  if (ep.requestBodySchema) {
    lines.push(`        if body is not None:`);
    lines.push(`            kwargs["json"] = body`);
  }

  lines.push(`        response = self.session.request("${ep.method}", url, **kwargs)`);
  lines.push(`        response.raise_for_status()`);
  lines.push(`        if response.status_code == 204:`);
  lines.push(`            return None`);
  lines.push(`        return response.json()`);

  return lines.join("\n");
}

function groupByTag(endpoints: ParsedEndpoint[]): Map<string, ParsedEndpoint[]> {
  const map = new Map<string, ParsedEndpoint[]>();
  for (const ep of endpoints) {
    const tag = ep.tags[0] ?? "default";
    if (!map.has(tag)) map.set(tag, []);
    map.get(tag)!.push(ep);
  }
  return map;
}

export function generatePythonSDK(
  spec: OpenAPISpec,
  endpoints: ParsedEndpoint[],
  outputDir: string,
  packageName: string
): void {
  const pkgSlug = toSnakeCase(packageName).replace(/-/g, "_");
  const pkgDir = path.join(outputDir, pkgSlug);
  fs.mkdirSync(pkgDir, { recursive: true });

  const baseUrl = spec.servers?.[0]?.url ?? "https://api.example.com";
  const tagGroups = groupByTag(endpoints);

  // ── models.py ─────────────────────────────────────────────────────────────
  let modelsContent = `# Auto-generated by sdkgen. Do not edit.\nfrom __future__ import annotations\nfrom dataclasses import dataclass\nfrom typing import Any, Dict, List, Optional\n\n`;

  if (spec.components?.schemas) {
    for (const [name, schema] of Object.entries(spec.components.schemas)) {
      modelsContent += schemaToDataclass(name, schema, spec) + "\n";
    }
  }

  fs.writeFileSync(path.join(pkgDir, "models.py"), modelsContent);

  // ── exceptions.py ─────────────────────────────────────────────────────────
  const exceptionsContent = `# Auto-generated by sdkgen. Do not edit.\n
class APIError(Exception):
    """Raised when the API returns a non-2xx response."""
    def __init__(self, status_code: int, message: str):
        super().__init__(f"API Error {status_code}: {message}")
        self.status_code = status_code
`;
  fs.writeFileSync(path.join(pkgDir, "exceptions.py"), exceptionsContent);

  // ── one module per tag ────────────────────────────────────────────────────
  const moduleNames: string[] = [];

  for (const [tag, eps] of tagGroups) {
    const modName = toSnakeCase(tag);
    moduleNames.push(modName);
    const className = `${toPascalCase(tag)}Client`;

    let content = `# Auto-generated by sdkgen. Do not edit.\nfrom __future__ import annotations\nimport requests\nfrom typing import Any, Dict, Optional\n\n\nclass ${className}:\n`;
    content += `    def __init__(self, base_url: str = "${baseUrl}", session: Optional[requests.Session] = None):\n`;
    content += `        self.base_url = base_url.rstrip("/")\n`;
    content += `        self.session = session or requests.Session()\n\n`;

    for (const ep of eps) {
      content += buildPyMethod(ep, spec) + "\n\n";
    }

    fs.writeFileSync(path.join(pkgDir, `${modName}.py`), content);
  }

  // ── __init__.py ────────────────────────────────────────────────────────────
  let initContent = `# Auto-generated by sdkgen. Do not edit.\nfrom __future__ import annotations\nimport requests\nfrom typing import Optional\n\n`;
  for (const [tag] of tagGroups) {
    const modName = toSnakeCase(tag);
    const className = `${toPascalCase(tag)}Client`;
    initContent += `from .${modName} import ${className}\n`;
  }
  initContent += `from .exceptions import APIError\nfrom .models import *\n\n`;

  const sdkClass = toPascalCase(pkgSlug) + "SDK";
  initContent += `\nclass ${sdkClass}:\n    """Main SDK client for ${spec.info.title}"""\n\n`;
  initContent += `    def __init__(self, base_url: str = "${baseUrl}", api_key: Optional[str] = None):\n`;
  initContent += `        self.session = requests.Session()\n`;
  initContent += `        if api_key:\n            self.session.headers.update({"Authorization": f"Bearer {api_key}"})\n`;

  for (const [tag] of tagGroups) {
    const modName = toSnakeCase(tag);
    const className = `${toPascalCase(tag)}Client`;
    initContent += `        self.${modName} = ${className}(base_url, self.session)\n`;
  }

  initContent += `\n__all__ = ["${sdkClass}", "APIError", ${moduleNames
    .map((m) => `"${toPascalCase(m)}Client"`)
    .join(", ")}]\n`;

  fs.writeFileSync(path.join(pkgDir, "__init__.py"), initContent);

  // ── setup.py ──────────────────────────────────────────────────────────────
  const setupPy = `# Auto-generated by sdkgen. Do not edit.
from setuptools import setup, find_packages

setup(
    name="${pkgSlug}",
    version="0.1.0",
    description="${spec.info.title} Python SDK",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=["requests>=2.28.0"],
)
`;
  fs.writeFileSync(path.join(outputDir, "setup.py"), setupPy);

  // ── requirements.txt ──────────────────────────────────────────────────────
  fs.writeFileSync(path.join(outputDir, "requirements.txt"), "requests>=2.28.0\n");

  // ── README.md ─────────────────────────────────────────────────────────────
  const firstTag = [...tagGroups.keys()][0];
  const firstClient = firstTag ? toSnakeCase(firstTag) : "default";
  const firstEp = endpoints[0];

  const readme = `# ${spec.info.title} Python SDK

> Auto-generated by **sdkgen** v0.1.0

## Install

\`\`\`bash
pip install .
\`\`\`

## Usage

\`\`\`python
from ${pkgSlug} import ${sdkClass}

client = ${sdkClass}(api_key="YOUR_TOKEN")

${firstEp ? `result = client.${firstClient}.${toSnakeCase(firstEp.operationId)}()` : ""}
\`\`\`

## Clients

${[...tagGroups.keys()].map((t) => `- \`${toSnakeCase(t)}\` — ${toPascalCase(t)}Client`).join("\n")}
`;
  fs.writeFileSync(path.join(outputDir, "README.md"), readme);
}
