import * as fs from "fs";
import * as path from "path";
import { OpenAPISpec, ParsedEndpoint } from "../types";
import { schemaToTsInterface, schemaToTsType, toCamelCase, toPascalCase } from "../utils/schema";

function buildMethodSignature(ep: ParsedEndpoint, spec: OpenAPISpec): string {
  const args: string[] = [];

  for (const p of ep.pathParams) {
    const tsType = p.schema ? schemaToTsType(p.schema, spec) : "string";
    args.push(`${toCamelCase(p.name)}: ${tsType}`);
  }

  if (ep.requestBodySchema) {
    const bodyType = schemaToTsType(ep.requestBodySchema, spec);
    const opt = ep.requestBodyRequired ? "" : "?";
    args.push(`body${opt}: ${bodyType}`);
  }

  if (ep.queryParams.length > 0) {
    const qFields = ep.queryParams
      .map((p) => {
        const t = p.schema ? schemaToTsType(p.schema, spec) : "string";
        return `${toCamelCase(p.name)}${p.required ? "" : "?"}: ${t}`;
      })
      .join("; ");
    args.push(`params?: { ${qFields} }`);
  }

  const returnType = ep.responseSchema
    ? `Promise<${schemaToTsType(ep.responseSchema, spec)}>`
    : "Promise<unknown>";

  const methodName = toCamelCase(ep.operationId);
  return `  async ${methodName}(${args.join(", ")}): ${returnType}`;
}

function buildMethodBody(ep: ParsedEndpoint): string {
  const lines: string[] = [];

  // Build URL
  let urlExpr = `\`\${this.baseUrl}${ep.path.replace(/{(\w+)}/g, (_, n) => `\${${toCamelCase(n)}}`)}\``;

  if (ep.queryParams.length > 0) {
    lines.push(`    const url = new URL(${urlExpr});`);
    lines.push(`    if (params) {`);
    for (const p of ep.queryParams) {
      const camel = toCamelCase(p.name);
      lines.push(`      if (params.${camel} !== undefined) url.searchParams.set('${p.name}', String(params.${camel}));`);
    }
    lines.push(`    }`);
    urlExpr = "url.toString()";
  }

  // Fetch call
  const hasBody = !!ep.requestBodySchema;
  lines.push(`    const res = await fetch(${ep.queryParams.length > 0 ? urlExpr : urlExpr}, {`);
  lines.push(`      method: '${ep.method}',`);
  lines.push(`      headers: {`);
  lines.push(`        'Content-Type': 'application/json',`);
  lines.push(`        ...this.defaultHeaders,`);
  lines.push(`      },`);
  if (hasBody) {
    lines.push(`      body: JSON.stringify(body),`);
  }
  lines.push(`    });`);
  lines.push(`    if (!res.ok) {`);
  lines.push(`      const error = await res.text().catch(() => res.statusText);`);
  lines.push(`      throw new APIError(res.status, error);`);
  lines.push(`    }`);
  lines.push(`    if (res.status === 204) return undefined as unknown as any;`);
  lines.push(`    return res.json();`);

  return lines.join("\n");
}

function groupByTag(endpoints: ParsedEndpoint[]): Map<string, ParsedEndpoint[]> {
  const map = new Map<string, ParsedEndpoint[]>();
  for (const ep of endpoints) {
    const tag = ep.tags[0] ?? "default";
    if (!map.has(tag)) map.set(tag, []);
    map.get(tag)!.push(ep);
  }
  return map;
}

export function generateTypeScriptSDK(
  spec: OpenAPISpec,
  endpoints: ParsedEndpoint[],
  outputDir: string,
  packageName: string
): void {
  fs.mkdirSync(outputDir, { recursive: true });
  const srcDir = path.join(outputDir, "src");
  fs.mkdirSync(srcDir, { recursive: true });

  const baseUrl = spec.servers?.[0]?.url ?? "https://api.example.com";

  // ── types.ts ──────────────────────────────────────────────────────────────
  let typesContent = `// Auto-generated by sdkgen. Do not edit.\n\n`;

  if (spec.components?.schemas) {
    for (const [name, schema] of Object.entries(spec.components.schemas)) {
      typesContent += schemaToTsInterface(name, schema, spec) + "\n";
    }
  }

  fs.writeFileSync(path.join(srcDir, "types.ts"), typesContent);

  // ── errors.ts ─────────────────────────────────────────────────────────────
  const errorsContent = `// Auto-generated by sdkgen. Do not edit.\n
export class APIError extends Error {
  constructor(public readonly status: number, message: string) {
    super(\`API Error \${status}: \${message}\`);
    this.name = 'APIError';
  }
}
`;
  fs.writeFileSync(path.join(srcDir, "errors.ts"), errorsContent);

  // ── client files per tag ──────────────────────────────────────────────────
  const tagGroups = groupByTag(endpoints);
  const clientNames: string[] = [];

  for (const [tag, eps] of tagGroups) {
    const className = `${toPascalCase(tag)}Client`;
    clientNames.push(className);

    let content = `// Auto-generated by sdkgen. Do not edit.\nimport { APIError } from './errors';\n\n`;

    const methods = eps
      .map((ep) => {
        const sig = buildMethodSignature(ep, spec);
        const body = buildMethodBody(ep);
        const deprecated = ep.deprecated ? "  /** @deprecated */\n" : "";
        const jsdoc = ep.summary
          ? `  /**\n   * ${ep.summary}${ep.description ? `\n   * ${ep.description}` : ""}\n   */\n`
          : "";
        return `${jsdoc}${deprecated}${sig} {\n${body}\n  }`;
      })
      .join("\n\n");

    content += `export class ${className} {\n`;
    content += `  constructor(\n    private readonly baseUrl: string = '${baseUrl}',\n    private readonly defaultHeaders: Record<string, string> = {}\n  ) {}\n\n`;
    content += methods + "\n}\n";

    fs.writeFileSync(path.join(srcDir, `${toCamelCase(tag)}.ts`), content);
  }

  // ── index.ts ──────────────────────────────────────────────────────────────
  let indexContent = `// Auto-generated by sdkgen. Do not edit.\n\nexport * from './types';\nexport * from './errors';\n`;
  for (const [tag] of tagGroups) {
    indexContent += `export * from './${toCamelCase(tag)}';\n`;
  }

  // Main SDK class that composes all clients
  indexContent += `\n`;
  indexContent += `import { ${clientNames.join(", ")} } from './';\n\n`;

  // Re-export a convenience SDK class
  const tagEntries = [...tagGroups.keys()];
  indexContent += `export class ${toPascalCase(packageName)}SDK {\n`;
  for (const tag of tagEntries) {
    indexContent += `  public readonly ${toCamelCase(tag)}: ${toPascalCase(tag)}Client;\n`;
  }
  indexContent += `\n  constructor(baseUrl = '${baseUrl}', headers: Record<string, string> = {}) {\n`;
  for (const tag of tagEntries) {
    indexContent += `    this.${toCamelCase(tag)} = new ${toPascalCase(tag)}Client(baseUrl, headers);\n`;
  }
  indexContent += `  }\n}\n`;

  fs.writeFileSync(path.join(srcDir, "index.ts"), indexContent);

  // ── package.json ──────────────────────────────────────────────────────────
  const pkg = {
    name: packageName,
    version: "0.1.0",
    description: `TypeScript SDK for ${spec.info.title}`,
    main: "dist/index.js",
    types: "dist/index.d.ts",
    scripts: {
      build: "tsc",
      typecheck: "tsc --noEmit",
    },
    devDependencies: {
      typescript: "^5.0.0",
    },
  };
  fs.writeFileSync(path.join(outputDir, "package.json"), JSON.stringify(pkg, null, 2));

  // ── tsconfig.json ─────────────────────────────────────────────────────────
  const tsconfig = {
    compilerOptions: {
      target: "ES2020",
      module: "commonjs",
      lib: ["ES2020"],
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      declaration: true,
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ["src/**/*"],
  };
  fs.writeFileSync(path.join(outputDir, "tsconfig.json"), JSON.stringify(tsconfig, null, 2));

  // ── README.md ─────────────────────────────────────────────────────────────
  const firstTag = tagEntries[0];
  const firstClient = firstTag ? toCamelCase(firstTag) : "default";
  const firstEp = endpoints[0];

  const readme = `# ${spec.info.title} TypeScript SDK

> Auto-generated by **sdkgen** v0.1.0

## Install

\`\`\`bash
npm install ${packageName}
\`\`\`

## Usage

\`\`\`typescript
import { ${toPascalCase(packageName)}SDK } from '${packageName}';

const client = new ${toPascalCase(packageName)}SDK('${baseUrl}', {
  Authorization: 'Bearer YOUR_TOKEN',
});

// Example
${firstEp ? `const result = await client.${firstClient}.${toCamelCase(firstEp.operationId)}();` : ""}
\`\`\`

## Clients

${tagEntries.map((t) => `- \`${toCamelCase(t)}\` — ${toPascalCase(t)}Client`).join("\n")}
`;
  fs.writeFileSync(path.join(outputDir, "README.md"), readme);
}
